# Generated by Django 5.1.4 on 2025-01-04 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0003_alter_userprofile_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='store',
        ),
    ]
