# Generated by Django 5.1.4 on 2025-01-04 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0004_remove_productimage_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courier',
            name='courier_name',
        ),
        migrations.AddField(
            model_name='courier',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='couriers', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courier',
            name='current_orders',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='courier',
            name='status_courier',
            field=models.CharField(max_length=32),
        ),
    ]
