# Generated by Django 5.1.4 on 2025-01-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0005_remove_courier_courier_name_courier_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courierreview',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
