# Generated by Django 5.1.4 on 2025-01-07 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0007_remove_userprofile_user_name_alter_storeimage_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
    ]
